#!/bin/sh
cd ..
# build 
make
make clean
# install
rm -rf /usr/doc/twelf
mkdir -p /usr/doc/twelf
cp -f README /usr/doc/twelf
cp -rf doc/* /usr/doc/twelf
rm -rf /usr/share/twelf
mkdir -p /usr/share/twelf
cp -rf bin /usr/share/twelf
cp -rf emacs /usr/share/twelf
cp -rf examples /usr/share/twelf
cp -rf examples-clp /usr/share/twelf
cp -rf tex /usr/share/twelf
/usr/share/twelf/bin/.mkexec /usr/bin/sml /usr/share/twelf twelf-server
ln -sf /usr/share/twelf/bin/twelf-server /usr/bin/twelf-server
