#!/bin/sh
cd ..
# build 
make -f mlton/Makefile
make -f mlton/Makefile clean
# install
rm -rf /usr/share/twelf
mkdir -p /usr/share/twelf
cp -rf bin /usr/share/twelf
cp -rf emacs /usr/share/twelf
cp -rf examples /usr/share/twelf
cp -rf examples-clp /usr/share/twelf
cp -rf tex /usr/share/twelf
cp -rf doc /usr/share/twelf
ln -sf /usr/share/twelf/bin/twelf-server /usr/bin/twelf-server
