structure Flit =
  Flit (structure Global = Global
        structure Word = Word32
        structure Pack = PackWord32Little
        structure IntSyn = IntSyn
        structure Whnf = Whnf
        structure Print = Print
	structure Names = Names
	structure Index = Index
	structure Table = IntRedBlackTree)
