structure Subordinate = 
  Subordinate (structure Global = Global
	       (*! structure IntSyn' = IntSyn !*)
	       structure Whnf = Whnf
	       structure Names = Names
	       structure MTable = MidRedBlackTree
	       structure CTable = CidRedBlackTree
	       structure MCTable = MidCidRedBlackTree
	       structure MCCTable = MidCidCidRedBlackTree
	       structure IntSet = IntSet);
