#!/bin/csh -f
echo "Copying info file"
cp -p twelf.info ../info/
#
echo "Copying dvi file"
cp -p twelf.dvi ../dvi/
#
echo "Copying ps file"
cp -p twelf.ps ../ps/
cp -p twelf.ps /afs/cs/project/twelf/www/guide/
#
echo "Copying ps.gz file"
gzip -c twelf.ps > twelf.ps.gz
cp -p twelf.ps.gz /afs/cs/project/twelf/www/guide/
#
echo "Copying pdf file"
echo "Is the PDF file really up-to-date?"
cp -p twelf.pdf ../pdf/
cp -p twelf.pdf /afs/cs/project/twelf/www/guide/
#
echo "Copying html files"
cp -p twelf_*.html ../html/
cp -p twelf_*.html /afs/cs/project/twelf/www/guide/
