structure Cover =
  Cover (structure Global = Global
	 structure IntSyn' = IntSyn
	 structure Whnf = Whnf
	 structure Abstract = Abstract
	 structure Unify = UnifyTrail
	 structure Constraints = Constraints
	 structure ModeSyn' = ModeSyn
	 structure Index = Index
         structure Names = Names
	 structure Paths = Paths
	 structure Print = Print
	 structure CSManager = CSManager);
