<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>preliminary Twelf mode</string>
	<key>fileTypes</key>
	<array>
		<string>elf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Twelf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while)\b</string>
			<key>name</key>
			<string>keyword.other.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%infix|%prefix|%postfix|%name|%subord|%freeze|%thaw|%abbrev|%clause|%define|%solve|%querytabled|%query|%tabled|%deterministic|%mode|%unique|%block|%worlds|%covers|%total|%terminates|%reduces|%theorem|%prove|%assert|%establish|%sig|%struct|%trustme|%where|%include|%open|%use)</string>
			<key>name</key>
			<string>keyword.control.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%(\w+)</string>
			<key>name</key>
			<string>invalid.illegal.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;-|-&gt;|\b(type)\b|\b(sigma)\b)</string>
			<key>name</key>
			<string>keyword.operator.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[:.]</string>
			<key>name</key>
			<string>keyword.operator.twelf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[{\[]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.twelf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[}\]]</string>
			<key>name</key>
			<string>meta.binding.twelf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-z!&amp;$^+/&lt;=&gt;?@~|#*`;,]|-|\\)[a-zA-Z0-9]*</string>
			<key>name</key>
			<string>meta.identifier.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z][a-zA-Z0-9]*</string>
			<key>name</key>
			<string>variable.other.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(\.\w+)+</string>
			<key>name</key>
			<string>variable.other.qualified.twelf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%\{</string>
			<key>end</key>
			<string>\}%</string>
			<key>name</key>
			<string>comment.block.twelf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%$|%[% \t\f].*$)</string>
			<key>name</key>
			<string>comment.line.percentage.twelf</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.twelf</string>
	<key>uuid</key>
	<string>146DB308-331A-412B-A2B6-BC692AF83245</string>
</dict>
</plist>
