name: Twelf Regression Suite

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          mkdir mlton && cd mlton
          curl -O -L https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz
          tar xzf mlton-20210117-1.amd64-linux-glibc2.31.tgz
          cd mlton-20210117-1.amd64-linux-glibc2.31 && sudo make install
          echo -e '#!/bin/bash\ngit rev-parse HEAD' > /tmp/svnversion
          chmod +x /tmp/svnversion
          sudo cp /tmp/svnversion /usr/local/bin

      - name: Run tests
        run: cd TEST && ./regression.sh
